spring.application.name=Spring AI
spring.ai.openai.api-key=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
